version: '3.3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=user-files
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data