spring:
  data:
    redis:
      port: 6379
      host: redis
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  url: http://minio:9000
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_ACCESS_SECRET}
  bucket:
    name: user-files