spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    hidden-method:
      filter:
        enabled: true
  application:
    name: cloudFileStorageDev
  data:
    redis:
      port: 6379
  session:
    timeout: 1800s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

minio:
  url: http://localhost:9000
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  bucket:
    name: dev-user-files