spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    hidden-method:
      filter:
        enabled: true
  application:
    name: cloudFileStorageProd
  data:
    redis:
      port: 6379
  session:
    timeout: 1800s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cloudstorage
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

minio:
  url: http://minio:9000
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  bucket:
    name: user-files